USER_FILE=/u02/feedaggrwebserver-data/users/user.xml
HOME_FEED_AGGR=/u02/tomcat/apache-tomcat-9.0.117
cat $USER_FILE | grep '</userFeedUrl' | grep https: | grep -v youtube | grep -v grep | sed 's/\s*<userFeedUrl>//g' | sed 's/<\/userFeedUrl.*//g' | sed 's/https:\/\///g' | sed 's/\/.*//g' | sort -k1 | uniq | while read url; do \
        $HOME_FEED_AGGR/import-certificate-of-site-into-jks.sh $url
done
